/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package week5_junit;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void myTest1() {
         
        assertEquals(2, 1 + 1);
        //assertEquals(expected, actual[, message])

   }
}
